services:
  - type: web
    name: mockape-site
    env: static
    buildCommand: npm install --no-optional --no-audit
    startCommand: npx http-server -p $PORT -o
    envVars:
      - key: NODE_ENV
        value: production
